### ISSUE TITLE
increase bounds

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [qfpl/parsers-megaparsec#4]
could you please update your bounds (ideally in a metarevision update) to

```
                     , megaparsec >= 6 && < 8.1
                     , semigroups >=0.9 && <0.20
```

which allows use of the latest versions of these packages, which are being shipped in LTS-15.

I confirmed that both compile, here are the relevant lines from my freezefile as proof

```
             any.megaparsec ==8.0.0,
             megaparsec -dev,
             any.semigroups ==0.19.1,
             semigroups +binary +bytestring -bytestring-builder +containers +deepseq +hashable +tagged +template-haskell +text +transformers +unordered-containers,
```

I also pinged the Hackage trustees so it's possible they might have done this while you're sleeping :smiley:

**Comment by gwils** [comment]
Merged #5 and revised on hackage. Thank you!
